title: <p align="center"> Hien Le, BSc (Hons) </p>
logo: "/images/HienLe-avatar.png?raw=true"
description:
  <p align="left">
  <a href="https://www.linkedin.com/in/h11le/">LinkedIn</a> |
  <a href="https://github.com/h11le">Github</a> 
  </p>
  
  <p align="left">
  Welcome! 
  <br>
  I am a Computer Science graduate from TMU on the brink of venturing into new technological frontiers. Throughout my academic journey, I have excelled in programming, data analysis, system design, and now eagerly anticipating my graduation this year.
  <br><br>
  </p>
  

theme: jekyll-theme-minimal
timezone: Canada/Toronto
future: true
